fix(management): addition of createAt, updatedAl & lastConnectionAt i…
gravitee-io/gravitee-management-rest-api pull request #1174
Opened 2020-09-18 12:50 UTC by leleueri

…n bean provided by /management/user endpoint

fix gravitee-io/issues#4300

2020-09-18 19:32 UTC, brasseld requested changes

2020-09-18 19:32 UTC, brasseld commented on gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/authentication/UserDetails.java
> +    private Date createdAt;
Please force the property name to `created_at` for output as we are doing for other entities (see https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/api/ApiEntity.java#L102).

2020-09-18 19:32 UTC, brasseld commented on gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/authentication/UserDetails.java
> +    private Date updatedAt;
Obviously, same here...

2020-09-18 19:32 UTC, brasseld commented on gravitee-management-api-idp/gravitee-management-api-idp-api/src/main/java/io/gravitee/management/idp/api/authentication/UserDetails.java
> +    private Date lastConnectionAt;
And finally :)

2020-09-18 19:32 UTC, brasseld commented on gravitee-management-api-rest/src/test/java/io/gravitee/management/rest/resource/CurrentUserResourceTest.java
> +                .containsKeys("createdAt", "updatedAt", "lastConnectionAt");
You should certainly change this also :)

2020-09-21 12:11 UTC, phiz71 approved these changes

2020-09-21 12:12 UTC, merged