feat(virtual-host): implement domain restriction
gravitee-io/gravitee-management-rest-api pull request #1207
Opened 2020-10-13 11:40 UTC by phiz71

If domain restrictions exists on current environment, virtual hosts must respect them,

Closes gravitee-io/issues#4308

2020-10-26 13:48 UTC, ytvnr reviewed
some remarks and questions

2020-10-26 13:49 UTC, phiz71 commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
> +     */
I agree. Will be removed.

2020-10-26 13:51 UTC, phiz71 commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/EnvironmentResource.java
> +    @ApiOperation(value = "Get an Environment", tags = {"Environment"})
It could but it won't be changed since `deleteEnv` and `createEnv` will be removed.

2020-10-26 13:52 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +        validateDomainRestrictions(virtualHosts);
OK. I propose to rename `validate` to `sanitizeAndValidate` and to return the virtualHosts collection.

2020-10-26 13:54 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +                    throw new InvalidVirtualHostException(null, domainRestrictions);
No :)

2020-10-26 13:57 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +    private boolean isValidDomainOrSubDomain(String domain, List<String> domainRestrictions) {
Maybe not in the release, but it could maybe be moved to `gravitee-common`.
@aelamrani wdyt ?

2020-10-28 15:30 UTC, aelamrani requested changes

2020-10-28 15:31 UTC, aelamrani commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +        validateDomainRestrictions(virtualHosts);
LGTM

2020-10-28 15:33 UTC, aelamrani commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +    private boolean isValidDomainOrSubDomain(String domain, List<String> domainRestrictions) {
If we can share it among AM and APIM, yes it can be useful

2020-10-28 15:44 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/InvalidVirtualHostException.java
> +        return "invalid-virtual-host";
Fixed

2020-10-28 15:44 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +        validateDomainRestrictions(virtualHosts);
Fixed

2020-10-28 16:02 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/VirtualHostServiceImpl.java
> +    private boolean isValidDomainOrSubDomain(String domain, List<String> domainRestrictions) {
We use classes from `com.google.guava`. I'm not sure it's a good idea to add this kind of dependancies in `gravitee-common`

2020-11-03 16:43 UTC, merged