feat: support tickets history
gravitee-io/gravitee-management-rest-api pull request #1229
Opened 2020-10-28 13:20 UTC by ytvnr

Fixes gravitee-io/issues#4435

2020-11-03 11:16 UTC, phiz71 requested changes

2020-11-03 11:16 UTC, phiz71 commented on gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/TicketsParam.java
> +    private String order;
See next comment in openapi.yaml

2020-11-03 11:16 UTC, phiz71 commented on gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
> +      operationId: search
getTickets

2020-11-03 11:16 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
> +                        final Ticket ticket = new Ticket(t);
why creating a new ticket ?

2020-11-03 11:16 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
> +                        Ticket ticket = new Ticket(t);
why creating a new ticket ?

2020-11-04 06:34 UTC, ytvnr commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
> +    public Page<TicketEntity> search(
resolved

2020-11-04 06:41 UTC, ytvnr commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
> +        TicketEntity ticketEntity = ticketService.findById(ticketId);
i replaced by getTicket

2020-11-04 06:42 UTC, ytvnr commented on gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/TicketsResource.java
> +    public Response search(
resolved

2020-11-04 06:43 UTC, ytvnr commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
> +                        final Ticket ticket = new Ticket(t);
indeed, no need.
resolved

2020-11-04 06:46 UTC, ytvnr commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
> +                        Ticket ticket = new Ticket(t);
resolved !

2020-11-04 13:38 UTC, ytvnr commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/TicketsParam.java
> +public class TicketsParam {
resolved

2020-11-04 13:39 UTC, ytvnr commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
> +import io.gravitee.repository.analytics.query.SortBuilder;
resolved

2020-11-04 13:56 UTC, ytvnr commented on gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/TicketsParam.java
> +    private String order;
done

2020-11-04 13:56 UTC, ytvnr commented on gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/resources/openapi.yaml
> +      operationId: search
done

2020-11-13 07:11 UTC, phiz71 requested changes

2020-11-13 07:11 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
> +                    .orElse(null);
should throw an exception instead

2020-11-13 07:11 UTC, phiz71 commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
> +            @ApiResponse(code = 500, message = "Internal server error")})
"404" is missing in the documentation

2020-11-13 07:40 UTC, ytvnr commented on gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/common/Sortable.java
> +    boolean getOrder();
resolved

2020-11-13 07:40 UTC, ytvnr commented on gravitee-rest-api-model/src/main/java/io/gravitee/rest/api/model/common/SortableImpl.java
> +    public boolean getOrder() {
resolved

2020-11-13 07:40 UTC, ytvnr commented on gravitee-rest-api-portal/gravitee-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/resource/param/TicketsParam.java
> +    private String field;
resolved

2020-11-13 07:40 UTC, ytvnr commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TicketServiceImpl.java
> +                    .orElse(null);
resolved

2020-11-13 07:40 UTC, ytvnr commented on gravitee-rest-api-management/gravitee-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/PlatformTicketsResource.java
> +            @ApiResponse(code = 500, message = "Internal server error")})
resolved

2020-11-13 08:06 UTC, phiz71 approved these changes

2020-11-13 09:34 UTC, merged