feat(cockpit): handle organization and environment commands
gravitee-io/gravitee-management-rest-api pull request #1230
Opened 2020-10-29 10:18 UTC by jhaeyaert

Closes gravitee-io/issues#4287

2020-12-03 09:12 UTC, ytvnr reviewed
just a remark on accessors

2021-01-13 10:33 UTC, phiz71 requested changes

2021-01-13 10:33 UTC, phiz71 commented on pom.xml
> +        <gravitee-repository.version>3.4.0-SNAPSHOT</gravitee-repository.version>
```suggestion
        <gravitee-repository.version>3.6.0-SNAPSHOT</gravitee-repository.version>
```

2021-01-13 20:28 UTC, phiz71 approved these changes

2021-01-14 14:54 UTC, phiz71 approved these changes

2021-01-14 14:54 UTC, merged