Handle API Promotion request
gravitee-io/gravitee-management-rest-api pull request #1537
Opened 2021-06-15 08:50 UTC by gaetanmaisse

**Issue**

https://github.com/gravitee-io/issues/issues/5526

**Description**

WIP

2021-06-16 09:15 UTC, phiz71 requested changes

2021-06-16 09:15 UTC, phiz71 commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/services/CockpitServiceImpl.java
> +            e.printStackTrace();
Maybe we could use a logger ;)

2021-06-16 18:38 UTC, gaetanmaisse commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/bridge/BridgeCommandFactory.java
> -        command.setTimeoutMillis(BRIDGE_OPERATION_TIMEOUT);
When testing with dev env of Cockpit I sometimes had some timeout when it was set to 3s 😞

2021-06-23 11:40 UTC, phiz71 approved these changes

2021-06-23 12:04 UTC, merged