Handle API promotion requests and expose them as Tasks
gravitee-io/gravitee-management-rest-api pull request #1548
Opened 2021-06-23 12:07 UTC by gaetanmaisse

**Issue**

https://github.com/gravitee-io/issues/issues/5527

**Description**
 
Handle API promotion requests and expose them as Tasks

2021-06-30 13:26 UTC, gaetanmaisse commented on gravitee-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/TaskServiceImpl.java
> +                    }
To remove as it's unneeded, all the info are in the task directly

2021-07-01 07:54 UTC, phiz71 requested changes

2021-07-01 07:54 UTC, phiz71 commented on gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
> +        when(userService.findByIdWithRoles(any())).thenReturn(getAUserEntity());
mock `environmentService` instead

2021-07-01 07:54 UTC, phiz71 commented on gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
> +        when(userService.findByIdWithRoles(any())).thenReturn(getAUserEntity());
mock environmentService instead

2021-07-01 07:54 UTC, phiz71 commented on gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
> +        when(userService.findByIdWithRoles(any())).thenReturn(getAUserEntity());
mock environmentService instead

2021-07-01 07:54 UTC, phiz71 commented on gravitee-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/promotion/PromotionTasksServiceImplTest.java
> +    }
useless

2021-07-01 09:36 UTC, phiz71 approved these changes

2021-07-01 09:38 UTC, merged